### ISSUE TITLE
Browser & Accessibility Testing

### ISSUE THREAD

**Issue by ishanb2001** [AlexanderTahtadjian/web-design-2-independent-project#10]
The website is mobile-friendly but had a few issues loading some of the resources

<img width="1664" alt="Screen Shot 2020-12-07 at 10 45 03 AM" src="https://user-images.githubusercontent.com/55193891/101371958-5d277f80-3879-11eb-8e97-bbe0dc90684e.png">
<img width="793" alt="Screen Shot 2020-12-07 at 10 45 15 AM" src="https://user-images.githubusercontent.com/55193891/101371974-61ec3380-3879-11eb-8ff3-ebe06b1110ba.png">

**Comment by AlexanderTahtadjian** [comment]
Ill look into fixing that problem. Thanks.
