### ISSUE TITLE
Extra Space Help

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/web-design-2-independent-project#12]
@hellachella
@HannahDelaney
I'm having some issues with some extra large white space gaps on my artwork page, and I don't know how they got there and I'm not sure how to fix them.
![Screenshot 2020-12-14 080929](https://user-images.githubusercontent.com/55193211/102084882-d2e49b80-3de3-11eb-9e83-c5baf219afd6.jpg)
![Screenshot 2020-12-14 080955](https://user-images.githubusercontent.com/55193211/102084883-d37d3200-3de3-11eb-821b-7fd8df16f054.jpg)

**Comment by HannahDelaney** [comment]
Hey Alexander, I had a look at your site and I couldn't see these spaces. Did you solve the problem? If so, awesome! Don't forget to close the issue. :)

**Comment by AlexanderTahtadjian** [comment]
I managed to solve it by commenting out some lines of code
