### ISSUE TITLE
Alt tags on android feedback

### ISSUE THREAD

**Issue by Thebeerz** [AlexanderTahtadjian/web-design-2-independent-project#6]
Alex!! I love this website! :D I especially liked the hover transition effect. One minor tweak: the text thats supossed to be on top of the image gets smushed when images are disabled. Here's a pic below of what it looks like :) 
![Screen Shot 2020-12-07 at 9 27 20 AM](https://user-images.githubusercontent.com/55193140/101362827-a2927f80-386e-11eb-80fd-770a5ad19978.png)

**Comment by AlexanderTahtadjian** [comment]
Ill try to fix that, thank you so much for your feedback.
