### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by laura-hopk** [AlexanderTahtadjian/web-design-2-independent-project#8]
Looks very nice on android chrome!
I did notice that your images don't have proper alt tags on them. Simple fix! Add something you the image tag in the html like: " alt="forest scene" ".
I also noticed that your images don't have placeholders! Again, easy to fix, just add a background colour to your images in the css.

I also noticed there is a lot of space between the images and the text on the artwork page. Not sure if you got to completing that portion yet! Otherwise it is looking good.

**Comment by AlexanderTahtadjian** [comment]
Thanks for the feed back Laura. I'll make sure to add the alt tags as well as the placeholders (since I just forgot to put them), and I'm aware of the enormous white space on the artwork page, and I don't know how that happened, I'm trying to fix that as we speak. Thanks for that.
